Repository basiqio/api-ref, pull requests merged in 2023-05, with the labels that each got.

#210 DX-350 Overall Percentage added as Credit and debit
  reports.yml
Labels: enhancement

#211 DX-354 Transaction EP missing SubClass Object
  data.yml
Labels: bug

#215 DX-335 Added Missing FName, MName & LName from Retrieve a User
  .github/CODEOWNERS
  .github/workflows/pr-lint.yml
  core.yml
Labels: bug

#216 DX-360 Size missing in Reports Transactions EP
  reports.yml
Labels: bug

#217 DX-358 Deployed New Webhooks Updated docs
  .DS_Store
  .github/CODEOWNERS
  .github/dependabot.yml
  .github/workflows/CI-pipeline.yml
  .github/workflows/auto-approve.yml
  .github/workflows/pr-lint.yml
  .github/workflows/syncdev.yml
  README.md
  core.yml
  data.yml
  draft-release/webhook.yml
  enrich.yml
  identity.yml
  payments.yml
  reports.yml
  services.yml
Labels: bug

#221 DX-346 accounts add docs for extending accounts ep with new cdr attributes
  data.yml
Labels: enhancement

#222 DX-346 Removed Inconsistency
  data.yml
Labels: bug

#223 DX-362 Exposing accountOwnership in Reports Accounts Section Only
  reports.yml
Labels: documentation

#224 DX-363 webhooks update swagger file to include 401 and 429 errors
  .github/workflows/CI-pipeline.yml
  README.md
  data.yml
  draft-release/webhooks.yml
  reports.yml
Labels: Develop

#226 DX-358 webhooks preparation docs
  .DS_Store
  draft-release/webhooks.yml
Labels: documentation, Develop

#228 DX-346 Extended Meta tag with accounts new metadata
  data.yml
Labels: documentation

#229 DX-364 webhooks update security schemes to jwt
  data.yml
  draft-release/webhooks.yml
Labels: bug, documentation, Develop

#230 DX-334 CI-Pipeline Update to Remove Releases
  .github/workflows/CI-pipeline.yml
Labels: dependencies

#231 DX-367 Extend Events with Event Types in Core API
  .github/workflows/CI-pipeline.yml
  draft-release/core.yml
Labels: dependencies, Develop

#232 DX-367 Updated Error details
  draft-release/core.yml
Labels: bug

#234 DX-367 extended events in core with events types
  core.yml
  draft-release/core.yml
Labels: documentation, enhancement

#236 DX-40X Replacing arrays with object for Loan & CreditCard
  data.yml
Labels: bug
