Repository basiqio/api-ref, pull requests merged in 2023-04, with the labels that each got.

#188 DX-315 Removed Oauth2 Security Schemes and replaced by Bearer JWT
  data.yml
Labels: bug

#190 DX-316 Fixed Bearer auto populated token
  reports.yml
Labels: bug

#192 DX-320 Update Invalid Filter docs with 400 Invalid Filter Error
  core.yml
  data.yml
  identity.yml
  services.yml
Labels: enhancement

#193 DX-321 Added Missing ME035 + ME039 Metrics
  reports.yml
Labels: documentation, enhancement

#195 DX-326 Update Security Schemas for Enrich and Identity
  enrich.yml
  identity.yml
Labels: bug

#197 DX-327 Refactoring Payment Yaml Code
  payments.yml
Labels: bug

#198 DX-328 Refactoring Oauth2 to Bearer JWT & Updating CI Payment pipelines
  .github/workflows/CI-pipeline.yml
  core.yml
  payments.yml
  services.yml
Labels: bug

#199 DX-321 Updated ME035 + ME039 formats from Money to Integer
  reports.yml
Labels: bug

#200 DX-318 Introducing Webhook to Draft Mode
  draft-release/webhook.yml
Labels: enhancement

#201 DX-330 webhooks docs refactor
  draft-release/webhook.yml
Labels: enhancement

#202 DX-332 Webhooks pipeline draft mode
  .github/workflows/syncdev.yml
  draft-release/webhooks.yml
Labels: enhancement

#203 DX-333 Updated Security schemes on draft mode
  draft-release/webhooks.yml
Labels: bug

#204 DX-335 Reports schema update for ME035
  reports.yml
Labels: bug, documentation

#205 Add more post examples without account details
  payments.yml
Labels: bug, documentation, enhancement

#206 DX-337 Updating DeployProd Pipeline for Payments
  .github/workflows/CI-pipeline.yml
Labels: enhancement

#207 DX-339 Added Beta flag to all reports EP
  reports.yml
Labels: documentation, enhancement

#208 DX-341 Update api docs for reports Retention period to 24 hours
  reports.yml
Labels: documentation, enhancement

#209 DX-340 Add pagination on List All reports with links.next
  reports.yml
Labels: documentation, enhancement
