Repository basiqio/api-ref, pull requests merged in 2023-03, with the labels that each got.

#155 DEVX-274-docs-accounts-ep-extended-with-credit-limit
  data.yml
Labels: enhancement

#156 DEVX-279 Introducting Retrieve a report Endpoint
  reports.yml
Labels: documentation, enhancement

#157 DEVX-280-reports-ep-remove-list-from-403-404-and-500-error-responses
  reports.yml
Labels: bug

#158 DEVX-282-reports-docs-expose-report-transactions-ep-in-swagger
  reports.yml
Labels: documentation, enhancement

#159 DEVX-282 Removed Links Object and cleaned the title
  reports.yml
Labels: bug

#160 DEVX-282 Removed Links Object and cleaned the title
  reports.yml
Labels: bug

#161 DEVX-284-reports-docs-exposing-account-ownership
  reports.yml
Labels: enhancement

#163 DX-285-report-docs-to-remove-links-and-add-schemas-for-accounts-&-transactions
  reports.yml
Labels: bug, documentation

#165 DX-287-docs-affordability-transactions-docs-missing-sub-class-object-…
  affordability.yml
Labels: bug, documentation

#167 DX-289-there-are-no-query-parameters-under-the-accounts-endpoint-for-…
  data.yml
Labels: bug, documentation

#166 DX-288-docs-refine-security-schema-for-affordability-ep
  affordability.yml
Labels: bug, documentation

#168 DX-291-report-docs-clean-tokens-and-add-transactions-json-object-miss…
  reports.yml
Labels: bug

#169 DX-290 Updated Reports EP with Accounts missing Attributes
  reports.yml
Labels: bug

#171 DX-293-reports-docs-fix-the-identity-ep-auth-schemas
  identity.yml
Labels: bug, documentation

#172 DSO-1143 add auto approve dependabot action
  .github/workflows/auto-approve.yml
  .github/workflows/pr-lint.yml
  LICENSE
Labels: enhancement

#174 DX-294 Fixing the Pipeline issues
  data.yml
  draft-release/core.yml
Labels: bug, documentation, enhancement

#175 DX dev
  .github/workflows/syncdev.yml
  draft-release/core.yml
Labels: enhancement

#176 DX-296 Changed Git Action runner from Ubuntu-latest to Self-hosted
  .github/workflows/pr-lint.yml
Labels: enhancement

#177 DX-297-api-ref-add-auto-tagging-and-releases
  .github/workflows/CI.yml
  .github/workflows/pr-lint.yml
Labels: enhancement

#178 DX-298 Tagging & Releases after Sync
  .github/workflows/CI.yml
  .github/workflows/sync.yml
Labels: enhancement

#181 DX-301-api-ref-update-codeowners-change-sync-yaml-file-to-run-release…
  .github/CODEOWNERS
  .github/workflows/CI-pipeline.yml
Labels: enhancement

#182 DX-299-reports-ep-add-median-attributes-to-groups-and-subgroups
  reports.yml
Labels: documentation, enhancement

#183 DX-302 Update User First Middle and Last Names with Additional CodeOwner
  .github/CODEOWNERS
  core.yml
Labels: bug

#184 DX-305 Report Endpoint updated with pagination to Transactions EP
  reports.yml
Labels: enhancement

#185 DX-307-reports-remove-oauth-2-security-schemas-from-retrieve-report-t…
  reports.yml
Labels: bug
